title: MES Lab @ Ewha
description: Mobile Embedded AI Systems Lab at Ewha Womans University

# disabled because we are using a custom domain
#baseurl: /business-frontpage 

color-scheme: "#006633" # Ewha Womans University green

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
